-- CREATE USER 'root'@'%' IDENTIFIED BY 'password';

-- GRANT ALL PRIVILEGES ON database.* TO 'root'@'%' IDENTIFIED BY 'password';

CREATE TABLE IF NOT EXISTS accounts (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(20) NOT NULL,
	email VARCHAR(50) NOT NULL,
	password VARCHAR(255) NOT NULL,
	isAdmin BOOLEAN DEFAULT 0,
	createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT usernameUnique UNIQUE (username),
	CONSTRAINT emailUnique UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS questionCategories (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(20) NOT NULL,
	CONSTRAINT nameUnique UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS questions (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	author VARCHAR(20) NOT NULL,
	category VARCHAR(20) NOT NULL,
	title VARCHAR(60) NOT NULL,
	description VARCHAR(255),
	isAnswered BOOLEAN DEFAULT 0,
	CONSTRAINT titleUnique UNIQUE (title),
	FOREIGN KEY (category) REFERENCES questionCategories(name),
	FOREIGN KEY (author) REFERENCES accounts(username)
);

CREATE TABLE IF NOT EXISTS answers (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	author VARCHAR(20) NOT NULL,
	questionId INT UNSIGNED NOT NULL,
	content TEXT NOT NULL,
	createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (author) REFERENCES accounts(username),
	FOREIGN KEY (questionId) REFERENCES questions(id)
);

